#!/usr/bin/env sh

# Layout
yabai -m config layout bsp

# Window settings
yabai -m config window_placement second_child

# Padding and Margin
yabai -m config top_padding 12
yabai -m config right_padding 12
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config window_gap 12

# Mouse Settings
yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier alt
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_drop_action swap

# Disable specific Apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off

echo "yabai configuration loaded.."
