#!/usr/bin/env bash

# Directories where to look for projects
REPOS_ROOT="$HOME/Repos"
CONFIG_ROOT="$REPOS_ROOT/personal/dotfiles/env/.config"
PROJECT_FOLDERS="$REPOS_ROOT/personal $REPOS_ROOT/corpus $REPOS_ROOT/master $CONFIG_ROOT"

selected=$(find $PROJECT_FOLDERS -mindepth 1 -maxdepth 1 -type d | fzf)
if [[ -z "$selected" ]]; then
    exit 0
fi

# Switch to tmux session weather you're already on tmux or not
switch_to() {
    local session_name=$1

    if [[ -z "$TMUX" ]]; then
        tmux attach-session -t  $session_name
    else 
        tmux switch-client -t $session_name
    fi
}

# Get a name appropriate for tmux session name
selected_name=$(basename $selected  | tr ":,. " "____")

if ! tmux has-session -t=$selected_name 2> /dev/null ; then
    tmux new-session -ds $selected_name -c $selected
    tmux send-keys -t $selected_name "ready-tmux" 
fi

switch_to $selected_name

